name: vesuvius
channels:
  - conda-forge
  - defaults
dependencies:
  # Various image processing tools
  - scikit-image
  - Pillow
  - tifffile
  # Storage/database tools
  - zarr
  # Numerical analysis tools
  - numpy
  - scipy
  # Plotting tools
  - plotly
  - matplotlib
  - jupyter-dash